[phases.setup]
nixPkgs = ['python310', 'gcc']

[phases.install]
cmds = ['python -m venv --copies /opt/venv', '. /opt/venv/bin/activate && pip install -r requirements.txt']

[phases.build]
cmds = []

[start]
cmd = 'python examples/web_interface.py'
